Write a python program using Numpy operation on

In [26]:
# 1. creating a Numpy Array

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [27]:
# 2. Converting a 1D array to 2D array

arr = np.array([3, 5, 7, 9, 11, 15, 18, 22])
print("Original 1D array : ", arr)

# Reshape the 1D array into a 2D array (2 rows, 4 columns)
arr2 = arr.reshape(2, 4)
print("Converted 1D array to 2D array")
print("2D array is : ", arr2)

Original 1D array :  [ 3  5  7  9 11 15 18 22]
Converted 1D array to 2D array
2D array is :  [[ 3  5  7  9]
 [11 15 18 22]]


In [ ]:
# 3. Slicing starting from the 3rd value to the end

arr = np.array([3, 5, 7, 9, 11, 12, 16, 17])
print("Slice starting from 3rd value to end")
print(arr[3:])


Slice starting from 3rd value to end
[ 9 11 12 16 17]


In [ ]:
# 4. Slice 0 to 4 index

arr = np.array([3, 5, 7, 9, 11, 12, 14, 15])
print("Slice 0 to 4 index")
print("0 to 4 index are : ", arr[0:5])


Slice 0 to 4 index
0 to 4 index are :  [ 3  5  7  9 11]


In [ ]:
# 5. Use negative Slicing

arr = np.array([3, 5, 7, 9, 11, 15, 18, 22])
print("Use negative slicing")
print("Negative Slicing value is : ", arr[-4:-2])

Use negative slicing
Negative Slicing value is :  [11 15]


In [31]:
# 6. Use step value using start and end vlaue is empty

arr = np.array([3, 5, 7, 9, 11, 12, 14, 15])
print("Use step value using start and end value is empty")
print(arr[::3])

Use step value using start and end value is empty
[ 3  9 14]


In [ ]:
# 7. Use Slicing with interval input

arr = np.array([3, 5, 7, 9, 11, 12, 14, 15])
print("Slicing with interval")
print("Slicing with interval is : ", arr[3::4])

Slicing with interval
Slicing with interval is :  [ 9 15]


In [ ]:
# 8. Use Slicing 2D array

arr = np.array([
	[3, 5, 6],
	[12, 14, 16]
])

print("Use Slicing a 2D arrays")
print("Slicing with 2D array is : ", arr[1, 0:2])

Use Slicing a 2D arrays
Slicing with 2D array is :  [12 14]


In [38]:
# 9. Slicing 3D array
arr = np.array([
	[
		[3, 5, 6],
		[7, 9, 10]
	],
	[
		[12, 13, 15],
		[13, 18, 18]
	]	
])

print("Slicing 3D array")
print("Slicing 3D array is", arr[0, 1, 0:2])


Slicing 3D array
Slicing 3D array is [7 9]


In [42]:
# 10. Find the data type of an array

arr1 = np.array([1, 2, 3])
arr2 = np.array([
	[1.8, 2.5, 3.1],
	[4.5, 6.1, 7.7]
])

arr3 = np.array([
	[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9]
])

print("datatype of array1 : ", arr1.dtype)
print("datatype of array2 : ", arr2.dtype)
print("datatype of array3 : ", arr3.dtype)

datatype of array1 :  int32
datatype of array2 :  float64
datatype of array3 :  int32


In [43]:
# 11. Reverse a numpy data

# Original array
data = np.array([4, 7, 12, 5, 9, 15])

# Reverse using slicing
reversed_data = data[::-1]
print("Reverse of the data : ", reversed_data)

Reverse of the data :  [15  9  5 12  7  4]


In [44]:
# 12. use Concatenate() to join two arrays

arr = np.array([4, 7, 12])
arr1 = np.array([5, 9, 15])

con = np.concatenate((arr, arr1))
print("Conatenating two arrays")
print("Concatenated arrays : ", con)

Conatenating two arrays
Concatenated arrays :  [ 4  7 12  5  9 15]


In [ ]:
# 13. Use Concatenate() with axis=1

# combine columns horizontally in arrays 
arr = np.array([
	[5, 9],
	[11, 12]
])

arr1 = np.array([
	[14, 15],
	[4, 5]
])

con = np.concatenate((arr, arr1), axis=1)
# axis = 1 → add columns (horizontal)
print("Concatenate with axis")
print(con)

Concatenate with axis
[[ 5  9 14 15]
 [11 12  4  5]]


In [ ]:
# 14. Use concatenate() with axis=0

# combines rows vertically in arrays
arr1 = np.array([[5, 9],
                 [11, 12]])

arr2 = np.array([[14, 15], 
                 [4, 5]])

# Concatenate along axis = 0 (vertical stacking)
concatenate_array = np.concatenate((arr1, arr2), axis=0)

print(f"Concatenated array (axis=0) : \n{concatenate_array}")

Concatenated array (axis=0) : 
[[ 5  9]
 [11 12]
 [14 15]
 [ 4  5]]


Stacking means placing arrays on top of each other or side by side to make a bigger array.

Stacking rows → one block on top of another.

Stacking columns → blocks placed next to each other.

In [55]:
# 15. Use np.stack() to join arrays

array1d_1 = np.array([2, 4, 7])
array1d_2 = np.array([1, 6, 3])

# Stack 1D array along a new axis (default axis=0 for new dimension)
stacked_array = np.stack((array1d_1, array1d_2), axis=0)
print(f"Stacked array (axis=0) :\n{stacked_array}")

# Stack 1D array along a new axis (axis=1 for new dimention)
stacked_array_axis1 = np.stack((array1d_1, array1d_2), axis=1)
print(f"Stacked array (axis=1) : \n{stacked_array_axis1}")



Stacked array (axis=0) :
[[2 4 7]
 [1 6 3]]
Stacked array (axis=1) : 
[[2 1]
 [4 6]
 [7 3]]


In [59]:
# Numpy operations

a = np.array([1, 2, 6])
b = np.array([8, 9, 10])

sum_result = a + b
diff_result = a - b
product_result = a * b
sum_arr = np.sum(a)
mean_arr = np.mean(a)
min_arr = np.min(a)
max_arr = np.max(a)
std_arr = np.std(a)
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((3, 3))


print("Sum of array : ", sum_result)
print("Difference of array : ", diff_result)
print("Product of array : ", product_result)
print("Sum of array : ", sum_arr)
print("Mean of a array : ", mean_arr)
print("Min of a array : ", min_arr)
print("Max of a array : ", max_arr)
print("Standard Deviation of a array : ", std_arr)
print("Zeros array : ", zeros_arr)
print("Ones array  : ", ones_arr)
print("Shape of array : ", a.shape)

Sum of array :  [ 9 11 16]
Difference of array :  [-7 -7 -4]
Product of array :  [ 8 18 60]
Sum of array :  9
Mean of a array :  3.0
Min of a array :  1
Max of a array :  6
Standard Deviation of a array :  2.160246899469287
Zeros array :  [[0. 0. 0.]
 [0. 0. 0.]]
Ones array  :  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape of array :  (3,)
