Write a python program using Numpy operation on

In [1]:
# 1. Creating a Numpy Array

import numpy as np
arr = np.array([1, 2, 3, 5, 7])
print(arr)

[1 2 3 5 7]


In [2]:
# 2. Converting a 1D array to 2D array

import numpy as np
arr = np.array([3, 5, 7, 9, 11, 15, 18, 22])
print("Original 1D array : ", arr)
# Reshape the 1D array into a 2D array (2rows, 4columns)
arr2 = arr.reshape(2, 4)
print("Converted 1D array to 2D array")
print("2D array is : ", arr2)

Original 1D array :  [ 3  5  7  9 11 15 18 22]
Converted 1D array to 2D array
2D array is :  [[ 3  5  7  9]
 [11 15 18 22]]


In [3]:
# 3. Slicing starting from the 3rd value to the End

import numpy as np
arr = np.array([3, 5, 7, 9, 11, 15, 18, 22])
print("Slicing starting from 3rd value to end")
print(arr[3:])

Slicing starting from 3rd value to end
[ 9 11 15 18 22]


In [4]:
# 4. Slice 0 to 4 index
import numpy as np
arr = np.array([3, 5, 6, 7, 8, 9, 11, 12])
print("Slice 0 to 4 index : ")
print("0 to 4 index are : ", arr[0:5])

Slice 0 to 4 index : 
0 to 4 index are :  [3 5 6 7 8]


In [5]:
# 5. Use negative Slicing
import numpy as np
arr = np.array([3, 5, 7, 9, 11, 15, 18, 22])
print("Use negative slicing")
print("Negative Slicing value is : ", arr[-4:-2])


Use negative slicing
Negative Slicing value is :  [11 15]


In [ ]:
# 6. Use Step value and use start and end value is empty

import numpy as np
arr = np.array([3, 4, 5, 6, 7, 8, 9, 10])
print("Use step value using start and end value is empty")
print(arr[::3])

Use step value using start and end value is empty
[3 6 9]


In [7]:
# 7. Use Slicing with interval Input
import numpy as np
arr = np.array([3, 4, 5, 7, 8, 10, 11, 12])
print("Slicing with interval")
print("Slicing with interval is : ", arr[0::4])

Slicing with interval
Slicing with interval is :  [3 8]


In [11]:
# 8. Use Slicing 2D array
import numpy as np
arr = np.array([
	[3, 5, 7, 9],
	[11, 15, 18, 22]
])

print("use Slicing a 2D array : ")
print("Slicing with 2D array is : ", arr[1][1:3])

use Slicing a 2D array : 
Slicing with 2D array is :  [15 18]


In [10]:
# 10. Use Slicing a 3D array
import numpy as np
arr = np.array([
	[
		[3, 4, 5],
		[6, 8, 9]
	],
	[
		[12, 17, 18],
		[19, 21, 22]
	]
])

print("Slicing 3D arrays")
print("Slicing 3D arrays is", arr[0][0][0:2])

Slicing 3D arrays
Slicing 3D arrays is [3 4]


In [13]:
# 10. Find the data type of an array
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([
	[1.8, 1.2],
	[5.6, 1.7]
])
arr3 = np.array([
	[1, 2, 5],
	[6, 8, 9],
	[11, 12, 16]
])

print("datatpe of arr1 : ", arr1.dtype)
print("datatype of arr2 : ", arr2.dtype)
print("datatype of arr3 : ", arr3.dtype)

datatpe of arr1 :  int32
datatype of arr2 :  float64
datatype of arr3 :  int32


In [14]:
# 11. Reverse a numpy data
# Original array
data = np.array([4, 7, 12, 5, 9, 15])
# Reverse using slicing
reversed_data = data[::-1]
print("Reverse of the data : ", reversed_data)

Reverse of the data :  [15  9  5 12  7  4]


In [15]:
# 12. Use Concatenate() to join two arrays
arr1 = np.array([4, 7, 12])
arr2 = np.array([5, 7, 18])
con = np.concatenate((arr1, arr2))
print("Concatenating two arrays")
print("Concatenated arrays : ", con)

Concatenating two arrays
Concatenated arrays :  [ 4  7 12  5  7 18]


In [16]:
# 13. Use Concatenate() with axis = 1
# Combine columns horizantally in arrays
arr1 = np.array([
	[5, 9],
	[11, 12]
])

arr2 = np.array([
	[14, 15],
	[4, 5]
])

con = np.concatenate((arr1, arr2), axis=1)
# axis = 1 : add columns (horizantal)
print("Concatenate with axis 1")
print(con)

Concatenate with axis 1
[[ 5  9 14 15]
 [11 12  4  5]]


In [17]:
# 14. Use concatenate() with axis = 0
# Combine rows vertically is arrays
arr1 = np.array([
	[5, 9],
	[11, 12]
])
arr2 = np.array([
	[14, 15],
	[4, 5]
])
# concatenate along axis = 0 (vertical stacking)
con = np.concatenate((arr1, arr2), axis=0)
print("Concatenate with axis = 0")
print(con)

Concatenate with axis = 0
[[ 5  9]
 [11 12]
 [14 15]
 [ 4  5]]


In [19]:
# 15. Use np.stack() to join arrays
arr1 = np.array([2, 4, 7])
arr2 = np.array([1, 6, 3])

# Stack 1D array along a new axis (default axis = 0 for new dimension)
stacked_a0 = np.stack((arr1, arr2), axis=0)
print("Stacked array in axis 0")
print(stacked_a0)

# Stack 1D array along axis 1
stacked_a1 = np.stack((arr1, arr2), axis=1)
print("Stacked array in axis 1")
print(stacked_a1)

Stacked array in axis 0
[[2 4 7]
 [1 6 3]]
Stacked array in axis 1
[[2 1]
 [4 6]
 [7 3]]


In [22]:
# Numpy operations

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum_result = a + b
diff_result = a - b
product_result = a * b
arr_sum = np.sum(a)
arr_mean = np.mean(a)
arr_min = np.min(a)
arr_max = np.max(a)
arr_std = np.std(a)
arr_median = np.median(a)

zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 3))

print(sum_result)
print(diff_result)
print(product_result)
print(arr_sum)
print(arr_mean)
print(arr_min)
print(arr_max)
print(arr_std)
print(arr_median)
print(zeros_array)
print(ones_array)
print(a.shape)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
6
2.0
1
3
0.816496580927726
2.0
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3,)
